### PR TITLE
Landsat GQA workflow integration

### PR DESCRIPTION
**Pull request by uchchwhash**
- Refactor to abstract over acquisition type
- Fix timeout error
- Fix `pandas` warning

### CODE REVIEW

**Review by ASVincent — APPROVED** [review]
Changes look good; can you verify with Sentinel 2 so can be confident of including this update with the processing version bump for Sentinel 2.
The improvements to the subprocess call would be good to have.

**Review by ASVincent — APPROVED** [review]
Changes look good.

Can you ensure that a test run is done with Sentinel-2 acquisition type as it would be good to include these changes in the processing version bump.

**Review by ASVincent — APPROVED** [review]
Changes look good.

Can you ensure that a test run is done with Sentinel-2 acquisition type as it would be good to include these changes in the processing version bump.

**Comment by uchchwhash** [comment]
Fixed Sentinel-2 issue encountered.

**Pull request merged**
